import type { UserRole, PermissionKey } from '@/types'

// Menu items visible per role
export const ROLE_MENUS: Record<UserRole, string[]> = {
  owner: [
    'dashboard',
    'kasir',
    'produk',
    'kategori',
    'supplier',
    'stok',
    'transaksi',
    'hutang',
    'laporan',
    'user',
    'cabang',
    'shift',
    'pengaturan',
    'backup',
    'theme',
  ],
  manager: [
    'dashboard',
    'kasir',
    'produk',
    'supplier',
    'stok',
    'hutang',
    'laporan',
    'user',
    'shift',
  ],
  staff: ['dashboard', 'kasir', 'hutang', 'stok', 'favorit', 'shift'],
}

// Default permissions per role
export const ROLE_DEFAULT_PERMISSIONS: Record<UserRole, PermissionKey[]> = {
  owner: [
    'add_product',
    'edit_product',
    'delete_product',
    'add_stock',
    'input_expense',
    'buy_gas',
    'take_cash',
    'edit_price',
    'export_data',
    'import_data',
    'view_report',
    'view_all_branches',
    'manage_users',
    'manage_branches',
    'manage_categories',
    'manage_suppliers',
    'delete_transaction',
    'backup_restore',
  ],
  manager: [
    'add_product',
    'edit_product',
    'add_stock',
    'input_expense',
    'view_report',
    'manage_suppliers',
    'manage_categories',
    'export_data',
  ],
  staff: [],
}

export const ALL_PERMISSIONS: Array<{ key: PermissionKey; label: string }> = [
  { key: 'add_product', label: 'Tambah Produk' },
  { key: 'edit_product', label: 'Edit Produk' },
  { key: 'delete_product', label: 'Hapus Produk' },
  { key: 'add_stock', label: 'Tambah Stok' },
  { key: 'input_expense', label: 'Input Pengeluaran' },
  { key: 'buy_gas', label: 'Membeli Elpiji' },
  { key: 'take_cash', label: 'Mengambil Uang Warung' },
  { key: 'edit_price', label: 'Edit Harga' },
  { key: 'export_data', label: 'Export Data' },
  { key: 'import_data', label: 'Import Data' },
  { key: 'view_report', label: 'Melihat Laporan' },
  { key: 'view_all_branches', label: 'Melihat Seluruh Cabang' },
  { key: 'manage_users', label: 'Kelola User' },
  { key: 'manage_branches', label: 'Kelola Cabang' },
  { key: 'manage_categories', label: 'Kelola Kategori' },
  { key: 'manage_suppliers', label: 'Kelola Supplier' },
  { key: 'delete_transaction', label: 'Hapus Transaksi' },
  { key: 'backup_restore', label: 'Backup & Restore' },
]
