import type { UserRole, PermissionKey } from '@/types'

// Menu items visible per role
export const ROLE_MENUS: Record<UserRole, string[]> = {
  developer: [
    'dashboard',
    'kasir',
    'produk',
    'kategori',
    'stok',
    'transaksi',
    'hutang',
    'laporan',
    'user',
    'cabang',
    'shift',
    'pengaturan',
    'backup',
    'theme',
  ],
  manager: [
    'dashboard',
    'kasir',
    'produk',
    'kategori',
    'stok',
    'transaksi',
    'hutang',
    'laporan',
    'user',
    'cabang',
    'shift',
    'pengaturan',
    'backup',
    'theme',
  ],
  staff: ['dashboard', 'shift'],
}

// Map menu keys to required permissions (optional, if not in ROLE_MENUS)
export const MENU_PERMISSIONS: Record<string, PermissionKey[]> = {
  kasir: ['access_kasir'],
  hutang: ['access_hutang'],
  produk: ['add_product', 'edit_product', 'delete_product'],
  kategori: ['manage_categories'],
  stok: ['add_stock'],
  laporan: ['view_report'],
  user: ['manage_users'],
  cabang: ['manage_branches'],
  backup: ['backup_restore'],
}

// Default permissions per role
export const ROLE_DEFAULT_PERMISSIONS: Record<UserRole, PermissionKey[]> = {
  developer: [
    'access_kasir',
    'access_hutang',
    'add_product',
    'edit_product',
    'delete_product',
    'add_stock',
    'input_expense',
    'buy_gas',
    'take_cash',
    'edit_price',
    'export_data',
    'import_data',
    'view_report',
    'view_all_branches',
    'manage_users',
    'manage_branches',
    'manage_categories',
    'delete_transaction',
    'backup_restore',
    'close_warung',
    'add_staff',
  ],
  manager: [
    'access_kasir',
    'access_hutang',
    'add_product',
    'edit_product',
    'delete_product',
    'add_stock',
    'input_expense',
    'buy_gas',
    'take_cash',
    'edit_price',
    'export_data',
    'import_data',
    'view_report',
    'view_all_branches',
    'manage_users',
    'manage_branches',
    'manage_categories',
    'delete_transaction',
    'backup_restore',
    'close_warung',
    'add_staff',
  ],
  staff: [
    'access_kasir',
    'access_hutang',
    'input_expense',
    'buy_gas',
    'take_cash',
  ],
}

export const ALL_PERMISSIONS: Array<{ key: PermissionKey; label: string }> = [
  { key: 'access_kasir', label: 'Akses Kasir' },
  { key: 'access_hutang', label: 'Akses Hutang' },
  { key: 'add_product', label: 'Tambah Produk' },
  { key: 'edit_product', label: 'Edit Produk' },
  { key: 'delete_product', label: 'Hapus Produk' },
  { key: 'add_stock', label: 'Tambah Stok' },
  { key: 'input_expense', label: 'Input Pengeluaran' },
  { key: 'buy_gas', label: 'Operasional' },
  { key: 'take_cash', label: 'Mengambil Uang Warung' },
  { key: 'close_warung', label: 'Tutup Warung' },
  { key: 'add_staff', label: 'Tambah Staff' },
  { key: 'edit_price', label: 'Edit Harga' },
  { key: 'export_data', label: 'Export Data' },
  { key: 'import_data', label: 'Import Data' },
  { key: 'view_report', label: 'Melihat Laporan' },
  { key: 'view_all_branches', label: 'Melihat Seluruh Cabang' },
  { key: 'manage_users', label: 'Kelola User' },
  { key: 'manage_branches', label: 'Kelola Cabang' },
  { key: 'manage_categories', label: 'Kelola Kategori' },
  { key: 'delete_transaction', label: 'Hapus Transaksi' },
  { key: 'backup_restore', label: 'Backup & Restore' },
]
